//------------------------------------------------------------------ general
export 'package:flutter/material.dart';
//------------------------------------------------------------- utils
export 'package:almajidoud/utils/colors.dart';
export 'package:almajidoud/utils/responsive.dart';
export 'package:almajidoud/utils/check_direction.dart';
//  --------------------------------------------------------------------- custom widgets
export 'package:almajidoud/custom_widgets/custom_description_text.dart';
export 'package:almajidoud/custom_widgets/responsive_sized_box.dart';
export  'package:almajidoud/custom_widgets/custom_build_body.dart';
//-------------------------------------------------------------   screens
//--------------------------------------------------------------------  plugins added to pubspec.yaml
export 'package:clippy_flutter/clippy_flutter.dart';
export 'package:syncfusion_flutter_sliders/sliders.dart';
export 'package:pie_chart/pie_chart.dart';
export 'package:smooth_star_rating/smooth_star_rating.dart';
export 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
export 'package:grouped_checkbox/grouped_checkbox.dart';
export 'package:carousel_pro/carousel_pro.dart';
export 'package:localize_and_translate/localize_and_translate.dart';
export  'package:flutter_neumorphic/flutter_neumorphic.dart';

export 'package:almajidoud/Base/shared_preference_manger.dart';

export 'package:almajidoud/Base/network-mappers.dart';
export 'package:almajidoud/Base/network_util.dart';
export 'package:almajidoud/Base/urls.dart';
export 'package:almajidoud/Base/validator.dart';

export 'package:almajidoud/Bloc/Authentication_Bloc/ForgetPasswordBloc/forget_password_bloc.dart';
export 'package:almajidoud/Helper/app_event.dart';
export 'package:almajidoud/Helper/app_state.dart';
export 'package:almajidoud/Repository/AuthenticationRepo/authentication_repository.dart';
export 'package:bloc/bloc.dart';
export 'package:almajidoud/Base/connectivity/network_indicator.dart';
export 'package:almajidoud/Base/safe_area/page_container.dart';
export 'package:almajidoud/custom_widgets/custom_animated_push_navigation.dart';
export 'package:almajidoud/screens/auth/login_with_phone_screen.dart';
export 'package:almajidoud/screens/auth/verification_code_screen.dart';
export 'package:almajidoud/Model/AuthenticationModel/user_info_model.dart';
export 'package:almajidoud/Model/AuthenticationModel/authentication_model.dart';
export 'package:almajidoud/custom_widgets/flushbar_widget.dart';
export 'package:almajidoud/custom_widgets/stagger_animation.dart';
export 'package:almajidoud/screens/auth/forget_password_screen.dart';
export 'package:almajidoud/screens/auth/sign_up_screen.dart';
export 'package:almajidoud/screens/intro/splash_screen.dart';
export 'package:localize_and_translate/localize_and_translate.dart';
export 'package:almajidoud/utils/check_direction.dart';
export 'package:almajidoud/custom_widgets/custom_push_named_navigation.dart';

export 'package:almajidoud/Model/AuthenticationModel/reset_password_model.dart';
export 'package:almajidoud/utils/fonts.dart';
export 'package:almajidoud/utils/static_data.dart';
export 'package:flushbar/flushbar.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:almajidoud/screens/auth/reset_password_screen.dart';
export 'package:almajidoud/screens/auth/sing_in_screen.dart';
export 'package:almajidoud/screens/home/home_screen.dart';
export 'package:almajidoud/screens/cart/cart_screen.dart';
export 'package:almajidoud/screens/location/location_screen.dart';
export 'package:almajidoud/screens/my_account/my_account_screen.dart';
export 'package:almajidoud/screens/notifications/notifications_screen.dart';
export 'package:almajidoud/screens/settings/settings_screen.dart';
export 'package:almajidoud/screens/categories/category_product/widgets/category_products_top_slider.dart';
export 'package:almajidoud/screens/categories/category_product/widgets/single_category_product_item.dart';
export 'package:almajidoud/screens/categories/category_product/category_products_screen.dart';
export 'package:almajidoud/utils/product_images.dart';
export 'package:almajidoud/Widgets/screen_app_bar.dart';
export 'package:almajidoud/Model/ReviewModel/product_review_model.dart';
export 'package:almajidoud/Repository/ReviewRepo/review_repository.dart';
export 'package:almajidoud/Bloc/Review_Bloc/reviews_bloc.dart';
